const sgMail = require("@sendgrid/mail");
const PDFDocument = require("pdfkit");
const { PassThrough } = require("stream");

// Set SendGrid API Key
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const createProfessionalPDF = (doc, details) => {
  // Page Border
  doc.rect(20, 20, 572, 752).stroke("#e5e7eb");

  // --- Header with Deep Blue Background ---
  doc.rect(20, 20, 572, 100).fill("#1e3a8a");
  
  // --- Logo Placeholder (White Circle with Brand initials) ---
  doc.fillColor("#ffffff").circle(60, 70, 30).fill();
  doc.fillColor("#1e3a8a").fontSize(25).text("AC", 42, 58, { bold: true });

  // --- Brand Name ---
  doc.fillColor("#ffffff")
     .fontSize(24)
     .text("Apna Clinic", 110, 45, { bold: true })
     .fontSize(10)
     .text("HEALTHCARE", 111, 75, { characterSpacing: 2 });
  
  // --- Header Badge ---
  doc.rect(400, 45, 172, 50, 5).fill("#2563eb");
  doc.fillColor("#ffffff")
     .fontSize(8)
     .text("RECEIPT NO: " + (details._id?.toString().slice(-8).toUpperCase() || "T-001"), 410, 55)
     .fontSize(12)
     .text("APPOINTMENT RECEIPT", 410, 70, { bold: true });

  // --- Section 1: Patient Information ---
  doc.fillColor("#1e3a8a")
     .fontSize(14)
     .text("PATIENT INFORMATION", 50, 150, { bold: true });
  doc.moveTo(50, 170).lineTo(562, 170).strokeWidth(1).stroke("#1e3a8a");

  // Information Grid
  const leftCol = 60;
  const rightCol = 320;
  let y = 190;

  const drawRow = (label, value, xPos, yPos) => {
    doc.fillColor("#6b7280").fontSize(9).text(label, xPos, yPos);
    doc.fillColor("#111827").fontSize(11).text(value || "N/A", xPos, yPos + 15, { bold: true });
  };

  drawRow("PATIENT NAME", details.patientName, leftCol, y);
  drawRow("APPOINTMENT DATE", details.date, rightCol, y);
  
  y += 50;
  drawRow("CONTACT NUMBER", details.phone, leftCol, y);
  drawRow("APPOINTMENT TIME", details.time, rightCol, y);

  y += 50;
  drawRow("EMAIL ADDRESS", details.patientEmail, leftCol, y);
  drawRow("PROBLEM / SYMPTOMS", details.problem && details.problem !== "undefined" ? details.problem : "General Consultation", rightCol, y);

  // --- Section 2: Hospital / Branch Details ---
  y += 60;
  doc.fillColor("#1e3a8a")
     .fontSize(14)
     .text("HOSPITAL & PROVIDER DETAILS", 50, y, { bold: true });
  doc.moveTo(50, y + 20).lineTo(562, y + 20).stroke("#1e3a8a");
  
  y += 40;
  doc.roundedRect(50, y, 512, 100, 8).fill("#f8fafc");
  doc.fillColor("#1e3a8a").fontSize(12).text(details.hospitalName, 70, y + 20, { bold: true });
  
  if (details.branchDetails) {
    doc.fillColor("#ef4444").fontSize(9).text("BRANCH OFFICE", 70, y + 38, { bold: true });
    doc.fillColor("#374151").fontSize(10).text(details.branchDetails.address, 70, y + 50, { width: 470 });
  } else {
    doc.fillColor("#374151").fontSize(10).text(details.location || "N/A", 70, y + 40, { width: 470 });
  }

  // --- Section 3: Support Information ---
  y += 130;
  doc.roundedRect(50, y, 512, 85, 5).dash(5, { space: 2 }).stroke("#cbd5e1").undash();
  doc.fillColor("#475569").fontSize(10).text("For Support & Queries:", 70, y + 20, { bold: true });
  
  doc.fillColor("#1e3a8a").fontSize(10)
     .text(`Email: ${details.supportEmail || "support@apnaclinic.com"}`, 70, y + 40)
     .text(`Contact: ${details.supportPhone || "+91 9876543210"}`, 300, y + 40);

  // --- Terms & Instructions ---
  y += 100;
  doc.fillColor("#9ca3af").fontSize(8)
     .text("Notes:", 50, y)
     .text("1. Please arrive at least 15 minutes before your scheduled time.", 50, y + 15)
     .text("2. Carry a valid photo ID and previous medical records if any.", 50, y + 28)
     .text("3. Cancellations should be made at least 2 hours in advance.", 50, y + 41);

  // --- Footer ---
  doc.rect(20, 742, 572, 30).fill("#1e3a8a");
  doc.fillColor("#ffffff").fontSize(9)
     .text("Generated by Apna Clinic HealthCare Ecosystem - Secure Medical Records", 20, 753, { align: "center", width: 572 });
};

const twilio = require("twilio");

const twilioClient = twilio(
  process.env.TWILIO_ACCOUNT_SID,
  process.env.TWILIO_AUTH_TOKEN
);

const sendWhatsAppNotification = async (phone, message) => {
  try {
    const textMessage = message || "Notification from Apna Clinic HealthCare";

    const formattedPhone = phone.startsWith("whatsapp:") 
      ? phone 
      : `whatsapp:${phone}`;

    console.log("Sending WhatsApp to:", formattedPhone);
    console.log("Message:", textMessage);

    await twilioClient.messages.create({
      from: process.env.TWILIO_WHATSAPP_NUMBER,
      to: formattedPhone,
      body: textMessage,
    });

    console.log("WhatsApp sent successfully");
  } catch (error) {
    console.error("Twilio WhatsApp Error:", error.message);
  }
};

const sendAppointmentEmail = async (patientEmail, bookingDetails, includePDF = true) => {
  try {
    let attachments = [];
    
    if (includePDF) {
      const doc = new PDFDocument({ margin: 50 });
      const stream = new PassThrough();
      doc.pipe(stream);
      createProfessionalPDF(doc, bookingDetails);
      doc.end();

      const chunks = [];
      for await (const chunk of stream) { chunks.push(chunk); }
      const pdfBuffer = Buffer.concat(chunks);
      
      attachments.push({
        content: pdfBuffer.toString("base64"),
        filename: "Appointment_Summary.pdf",
        type: "application/pdf",
        disposition: "attachment",
      });
    }

    const msg = {
      to: patientEmail,
      from: process.env.SENDGRID_SENDER_EMAIL,
      subject: `Appointment Update: ${bookingDetails.status.toUpperCase()} - ${bookingDetails.hospitalName}`,
      text: bookingDetails.msg || `Hello ${bookingDetails.patientName},\n\nYour appointment at ${bookingDetails.hospitalName} status is now: ${bookingDetails.status}.\n\nThank you for using Apna Clinic HealthCare!`,
      attachments: attachments,
    };

    await sgMail.send(msg);
    console.log(`Email sent: ${bookingDetails.status} to ${patientEmail} via SendGrid (PDF: ${includePDF})`);
  } catch (error) {
    console.error("SendGrid Mailer Error:", error.response ? error.response.body : error);
  }
};

const sendHospitalApprovalEmail = async (hospitalEmail, hospitalName, status) => {
  try {
    const message = `Hello ${hospitalName},\n\nYour hospital registration status has been updated to: ${status.toUpperCase()}.\n\n${status === 'approved' ? 'You can now log in and manage your dashboard.' : 'Please contact support for more details.'}\n\nThank you,\nBookVisit Team`;

    const msg = {
      to: hospitalEmail,
      from: process.env.SENDGRID_SENDER_EMAIL,
      subject: `Hospital Status Update: ${status.toUpperCase()}`,
      text: message,
    };

    await sgMail.send(msg);
    console.log(`Email sent to hospital: ${status} to ${hospitalEmail} via SendGrid`);
  } catch (error) {
    console.error("SendGrid Hospital Mailer Error:", error.response ? error.response.body : error);
  }
};

const sendHospitalPendingEmail = async (hospitalEmail, hospitalName) => {
  try {
    const msg = {
      to: hospitalEmail,
      from: process.env.SENDGRID_SENDER_EMAIL,
      subject: `Hospital Registration: UNDER REVIEW`,
      text: `Hello ${hospitalName},\n\nYour hospital registration is currently UNDER REVIEW.\n\nOur admin team will verify your details and approve it within 24 hours.\n\nYou will receive another email once it is approved.\n\nThank you for joining BookVisit!`,
    };

    await sgMail.send(msg);
    console.log(`Pending email sent to hospital: ${hospitalName} to ${hospitalEmail} via SendGrid`);
  } catch (error) {
    console.error("SendGrid Hospital Pending Mailer Error:", error.response ? error.response.body : error);
  }
};

module.exports = { 
  sendAppointmentEmail, 
  sendWhatsAppNotification, 
  sendHospitalApprovalEmail,
  sendHospitalPendingEmail 
};
